Dashboard Page Not Updating
unfoldingWord-dev/tx-manager pull request #120
Opened 2017-07-31 03:25 UTC by bspidel

The Failed Jobs list on the dashboard page is not loading recent entries

Issue 617

@richmahn Please review. This code works against dev-tx-job but needs refactored to fit your tx-manager paradigm.

2017-07-31 16:14 UTC, PhotoNomad0 requested changes

2017-07-31 16:14 UTC, PhotoNomad0 commented on libraries/manager/manager.py
> +            job_failures = self.get_failures()
Need to pass max_failures as parameter so count is not hard coded to 10.

2017-07-31 16:14 UTC, PhotoNomad0 commented on libraries/manager/manager.py
> +            Limit=10)
Need to change 10 to a parameter of getFailures() such as max_count

2017-07-31 16:14 UTC, PhotoNomad0 commented on libraries/manager/manager.py
> +        return client.query( TableName=u'dev-tx-job',
This should not be hard coded to 'dev-tx-job'.  Use self.job_table_name.

2017-08-01 12:32 UTC, PhotoNomad0 requested changes

2017-08-01 12:32 UTC, PhotoNomad0 commented on libraries/manager/manager.py
> +            ExpressionAttributeNames = {"#stts": "status"},
@bspidel If you change the index to have secondary sort key on created_at, and then add to the query ScanIndexForward = False, then the most recent failures will be read first.

2017-08-03 09:32 UTC, PhotoNomad0 approved these changes

2017-08-08 14:06 UTC, PhotoNomad0 commented
@bspidel - Did some cleanup on test cases in PR to add language report to Dashboard.  These are now in develop.

2017-09-21 18:51 UTC, closed without merging

2017-09-21 18:52 UTC, richmahn commented
Not needed any more.