WIP: Feature 665/usfm linter
unfoldingWord-dev/tx-manager pull request #126
Opened 2017-08-15 17:36 UTC by PhotoNomad0

Issue: https://github.com/unfoldingWord-dev/door43.org/issues/665

Changes:
- Pulled in Bible classes from uw-publish to use in checker.  
- Renamed bible classes to be USFM classes.
- Tweaked code and regex to capture more errors.

2017-08-19 13:58 UTC, PhotoNomad0 commented
@richmahn - ready for review.  Think it is time to disable InteliJ warnings of camel case variable/method names, because I don't want the fix the case of several hundred methods in the included code.

2017-08-21 15:43 UTC, richmahn requested changes
- A few code changes
- Does not match requirements - do not need to report missing books, only missing book titles.

2017-08-21 15:43 UTC, richmahn commented on libraries/checkers/usfm_checker.py
> +    def __init__(self, preconvert_dir, converted_dir, log=None):
It's always best to not to specifically name variables used by the parent init, as those may change (which they have in my branch). Do this instead for the first two lines:
```
    def __init__(self, *args, **kwargs):
        super(UsfmChecker, self).__init__(*args, **kwargs)
```

2017-08-21 15:43 UTC, richmahn commented on libraries/checkers/usfm_checker.py
> +                if f[-3:].lower() != 'sfm':  # only usfm files
What I'd do here, as I do in markdown, is:

```if os.path.splitext(f)[1].lower() != '.usfm':```

splitext always give a two item list, with the second being the extension with a preceding '.'

2017-08-21 15:43 UTC, richmahn commented on libraries/checkers/usfm_checker.py
> +            self.warn_on_missing_books(self.found_books)
I don't find anywhere in the requirements to care if a whole book is missing, only its title is missing.

2017-08-21 15:56 UTC, jag3773 commented on libraries/checkers/usfm_checker.py
> +            self.warn_on_missing_books(self.found_books)
Correct @richmahn, we will often have projects with multiple books but not all books.  This is OK.

2017-08-21 17:58 UTC, richmahn approved these changes
LGTM

2017-08-21 17:59 UTC, merged