Feature/issue 580 chapter ordering
unfoldingWord-dev/tx-manager pull request #135
Opened 2017-08-29 15:44 UTC by bspidel

sort field may be in middle of a path so break it out as sort key via python lambda function making it a 0 padded right justified field.

2017-08-29 18:34 UTC, richmahn requested changes
Unneeded glob call

No test case to verify chapters are ordered numerically

2017-08-29 18:34 UTC, richmahn commented on libraries/resource_container/ResourceContainer.py
> +            g = glob(os.path.join(self.dir, p.path, '*')
I don't think you need this since you do it again below.

2017-08-29 18:34 UTC, richmahn commented on libraries/resource_container/ResourceContainer.py
> +            for d in sorted(glob(os.path.join(self.dir, p.path, '*')),key=lambda path: '{:0>6}'.format(os.path.basename(path))):
Make sure there is a test case that verifies ordering here is done numerically. Have it preprocess a zip file from a PSA repo.

2017-08-29 18:48 UTC, richmahn commented on libraries/resource_container/ResourceContainer.py
> +            for d in sorted(glob(os.path.join(self.dir, p.path, '*')),key=lambda path: '{:0>6}'.format(os.path.basename(path))):
Make test case with: https://git.door43.org/tx-manager-test-data/ceb_psa_text_ulb_L3

2017-08-29 18:53 UTC, richmahn commented on libraries/resource_container/ResourceContainer.py
> +            for d in sorted(glob(os.path.join(self.dir, p.path, '*')),key=lambda path: '{:0>6}'.format(os.path.basename(path))):
Also, while pretty much the same thing, this is a bit more readable:

`key=lambda path: os.path.basename(path).zfill(3)`

(and we only really need to pad 3 0s as no book has # of books in the thousands).

2017-08-29 21:02 UTC, bspidel commented
Made requested changes. Extra line was debug. Good catch.

2017-08-29 21:58 UTC, bspidel commented
Added test case for chapter ordering

2017-09-01 14:19 UTC, richmahn approved these changes
LGTM

2017-09-01 14:19 UTC, merged