Feature/issue 679 update usfm linter output
unfoldingWord-dev/tx-manager pull request #165
Opened 2017-09-26 15:35 UTC by bspidel

Added some aserts to check format of warnings

2017-09-26 17:03 UTC, richmahn approved these changes
Sorry, noticed one problem...

2017-09-26 17:07 UTC, richmahn requested changes
Need to follow coding standards of tx-manager: no `u` prefix before strings (everything is already unicode) and no spaces after `(`s and before `)`s.

2017-09-26 17:07 UTC, richmahn commented on tests/linter_tests/test_usfm_linter.py
> +        self.assertEqual( linter.log.warnings[0], u'PHP  PH -  - Invalid ID' )
We don't put u'' in front of our strings since we declare unicode a the top of every file.  Please remove all u prefix to strings.

2017-09-26 17:07 UTC, richmahn commented on tests/linter_tests/test_usfm_linter.py
> +        self.assertEqual( linter.log.warnings[0], u'PHP  PH -  - Invalid ID' )
Also, please remove spaces after ( and before ). We need to stick to standard. I keep having to go through removing these spaces, as it also keep being flagged by Intellij's linter.

2017-09-26 18:27 UTC, bspidel commented
Made requested changes.

2017-09-27 20:16 UTC, PhotoNomad0 approved these changes

2017-09-27 20:16 UTC, merged