title_wrong_on_converted_repo
unfoldingWord-dev/tx-manager pull request #177
Opened 2017-10-05 22:08 UTC by bspidel

add resource types to resource map

Issue-759

2017-10-11 13:11 UTC, richmahn requested changes
Lowercase the `T` of `Translation`

2017-10-11 13:11 UTC, richmahn commented on libraries/resource_container/ResourceContainer.py
> +        'title': 'OBS TranslationNotes',
Lowercase the `T` of `Translation`

2017-10-11 13:11 UTC, richmahn commented on libraries/resource_container/ResourceContainer.py
> +        'title': 'OBS TranslationQuestions',
Lowercase the `T` of `Translation`

2017-10-11 15:18 UTC, bspidel commented
@richmahn Made case change you requested

2017-10-12 12:13 UTC, richmahn approved these changes
LGTM

2017-10-12 12:14 UTC, merged