Separates resource creation in s3_handler's init
unfoldingWord-dev/tx-manager pull request #37
Opened 2017-03-17 20:00 UTC by richmahn

Adds a setup_resources() called by s3_handler.py's `__init__()` function so that it can be mocked if needed.

2017-03-17 20:15 UTC, richmahn commented
Again, since s3_handler has an issue to add testing, the lower coverage should be ignored.

2017-03-20 02:29 UTC, phillip-hopper requested changes
Even if the tests won't run on Travis, you should still write tests that pass locally, and then skip them on Travis with
```
@unittest.skipIf("TRAVIS" in os.environ and os.environ["TRAVIS"] == "true", "Skipping this test on Travis CI.")
```

2017-03-21 03:45 UTC, richmahn commented
@phillip-hopper The problem isn't that tests can't be run on Travis-CI, but that there is another issue in the backlog for tests to be written. Another PR was accepted since we these issues aren't to write those tests.

2017-03-21 12:03 UTC, richmahn commented
@phillip-hopper Added an s3_handler test anyway. Runs locally.

2017-03-21 15:39 UTC, phillip-hopper approved these changes
LGTM 👍

2017-03-21 15:39 UTC, merged