Fixes error in client_callback (self.self.job.output)
unfoldingWord-dev/tx-manager pull request #38
Opened 2017-03-17 20:13 UTC by richmahn

Fixes the line of code `self.self.job.output` so callback can run. Adds some print statements to help in debugging on AWS.

2017-03-17 21:25 UTC, bspidel reviewed
LGTM

2017-03-17 21:27 UTC, bspidel approved these changes
again it LGTM

2017-03-21 15:46 UTC, phillip-hopper requested changes
Unit tests needed.

2017-03-22 15:07 UTC, phillip-hopper approved these changes

2017-03-22 15:07 UTC, merged