Fixes typo in deployer and adds logging statements, removes code for navigation
unfoldingWord-dev/tx-manager pull request #41
Opened 2017-03-21 13:40 UTC by richmahn

Fixes a type

Adds some print statements for logging/debuggin

templater.py has some code for the book navigation that shouldn't be in there yet, so removed.

2017-03-21 15:52 UTC, bspidel approved these changes
LGTM

2017-03-21 17:13 UTC, phillip-hopper requested changes
Unit tests?

2017-03-21 23:40 UTC, richmahn commented
Still doesn't make sense to fix one typo to then have to write all the unit tests for a package, but guess will do. Holds back the pipeline working for development though.

2017-03-22 14:36 UTC, phillip-hopper approved these changes

2017-03-22 14:36 UTC, merged