Feature/213 solidify badge statuses 5
unfoldingWord-dev/tx-manager pull request #50
Opened 2017-03-28 17:25 UTC by PhotoNomad0

Fix issue https://github.com/unfoldingWord-dev/door43.org/issues/213 solidify badge statuses 5

Changes:
Fix to return errors and warnings generated by OBSInspection of each file.
Md2HtmlConverter - added check for missing chapters. 
TestMd2HtmlConverter - added test cases for empty chapter, missing chunk, missing chapter.

2017-03-28 19:22 UTC, richmahn requested changes
See my line comments

2017-03-28 19:22 UTC, richmahn commented on tests/converter_tests/test_md2html_converter.py
> +
Let's do one blank line between functions in a class

2017-03-28 19:22 UTC, richmahn commented on tests/converter_tests/test_md2html_converter.py
> +
Ditto here about one blank line

2017-03-28 19:22 UTC, richmahn commented on converters/md2html_converter.py
> +                found_chapters[base_name] = True
Where is this used later?

2017-03-28 19:32 UTC, PhotoNomad0 commented on converters/md2html_converter.py
> +                found_chapters[base_name] = True
Below, starting in line 68.

2017-03-28 19:34 UTC, PhotoNomad0 commented on tests/converter_tests/test_md2html_converter.py
> +
sure

2017-03-29 19:13 UTC, richmahn approved these changes

2017-03-30 11:45 UTC, phillip-hopper requested changes

2017-03-30 11:45 UTC, phillip-hopper commented on tests/door43_tools_tests/test_usfm_preprocessor.py
> +            self.out_dir = tempfile.mkdtemp(prefix='output_')
The indentation looks wrong here.

2017-03-30 14:20 UTC, PhotoNomad0 commented on tests/door43_tools_tests/test_usfm_preprocessor.py
> +            self.out_dir = tempfile.mkdtemp(prefix='output_')
oops

2017-03-30 14:23 UTC, PhotoNomad0 commented
@phillip-hopper - fixed what you found

2017-03-30 16:37 UTC, phillip-hopper approved these changes
LGTM 👍

2017-03-30 16:37 UTC, merged