Issue 431: add job counts to dashboard
unfoldingWord-dev/tx-manager pull request #63
Opened 2017-05-09 18:35 UTC by PhotoNomad0

Issue https://github.com/unfoldingWord-dev/door43.org/issues/431: add job counts to dashboard

Changes:
- TxManager - added job counts per module and total. 
- DashboardTest - new unit test for TxManager.generate_dashboard()

2017-05-10 13:04 UTC, phillip-hopper requested changes

2017-05-11 14:26 UTC, PhotoNomad0 commented on manager/manager.py
> +                    '<tr id="' + item['name'] + '"><td class="hdr" colspan="2">' + str(moduleName) + '</td></tr>',
Thanks - good catch.

2017-05-11 14:30 UTC, PhotoNomad0 commented on manager/manager.py
> +                    '<tr id="' + item['name'] + '"><td class="hdr" colspan="2">' + str(moduleName) + '</td></tr>',
@phillip-hopper made requested changes.

2017-05-11 20:53 UTC, phillip-hopper approved these changes
LGTM 👍

2017-05-11 20:53 UTC, merged