Feature - Issue 560 - Merges tx-manager-lambda into tx-manager
unfoldingWord-dev/tx-manager pull request #91
Opened 2017-06-14 18:12 UTC by richmahn

Open for discussion/review. Didn't change the README.rst at all except to add the two sections that are useful from tx-manager-lambda's README.rst and put them at the bottom. README should be worked on once all is properly in place.

Let me know if I missed anything.

2017-06-14 18:13 UTC, richmahn commented
Also to note, this did deploy to the `test` environment with no problem and the API works, e.g. https://test-api.door43.org/tx https://test-api.door43.org/dashboard

2017-06-19 21:00 UTC, phillip-hopper requested changes
No changes requested yet. Just wanted to let you know the code review is in progress.

2017-06-19 21:16 UTC, phillip-hopper requested changes
Still waiting for instructions on how to run acceptance tests locally. Currently it fails with this message: 
```
AssertionError: GOGS_USER_TOKEN is missing in environment
```

2017-06-19 21:16 UTC, phillip-hopper commented on deploy.sh
> +#!/usr/bin/env bash
This file is not executable, mod is 0664.

2017-06-19 21:16 UTC, phillip-hopper commented on integration_test.sh
> +#!/usr/bin/env bash
This file is not executable, mod is 0664.

2017-06-19 21:16 UTC, phillip-hopper commented on travis-install-apex.sh
> +#!/usr/bin/env bash
This file is not executable, mod is 0664.

2017-06-19 21:16 UTC, phillip-hopper commented on register-modules.sh
> +#!/usr/bin/env bash
This file is not executable, mod is 0664.

2017-06-20 19:34 UTC, richmahn commented on register-modules.sh
> +#!/usr/bin/env bash
Ok, fixing file permissions. As for running locally, The tests are all I got, but that is unit testing. I then use the test AWS account and deploy it there when testing everything together.

2017-06-20 19:37 UTC, richmahn commented on deploy.sh
> +#!/usr/bin/env bash
fixed

2017-06-20 20:17 UTC, phillip-hopper approved these changes

2017-06-20 20:17 UTC, merged