Fix 556/repo conversion times out
unfoldingWord-dev/tx-manager pull request #92
Opened 2017-06-16 12:06 UTC by PhotoNomad0

Added support for splitting conversion into multiple parts.
bible conversions are split into separate conversions per book.

2017-06-17 12:58 UTC, phillip-hopper requested changes

2017-06-17 12:58 UTC, phillip-hopper commented on client/client_callback.py
> +        self.logger.debug('Callback for comming {0}...'.format(s3_commit_key))
Is `comming` a typo?

2017-06-17 12:58 UTC, phillip-hopper commented on client/client_callback.py
> +    def downloadFile(self, converted_zip_file, converted_zip_url):
What is the purpose of this function? It appears to just call another function.

2017-06-17 12:58 UTC, phillip-hopper commented on client/client_callback.py
> +    def cdnDownloadFile(self, cdn_handler, s3_part_key, filePath):
What is the purpose of this function? It appears to just call another function.

2017-06-17 12:58 UTC, phillip-hopper commented on client/client_callback.py
> +    def getFinishedParts(self, cdn_handler, s3_commit_key):
What is the purpose of this function? It appears to just call another function.

2017-06-17 12:58 UTC, phillip-hopper commented on client/client_callback.py
> +    def cdnGetJsonFile(self, cdn_handler, project_json_key):
What is the purpose of this function? It appears to just call another function.

2017-06-17 12:58 UTC, phillip-hopper commented on tests/manager_tests/test_manager.py
> +        expectedCount = "4"
Is there a reason we are expecting integers to be cast as strings?

2017-06-19 16:09 UTC, richmahn requested changes
Would be good to standardize variable names, using lowercase and underscores.

2017-06-19 16:09 UTC, richmahn commented on client/client_callback.py
> +        self.tempDir = tempfile.mkdtemp(suffix="", prefix="client_callback_")
As discussed on Slack, it is helpful for other programmers to at least have all variable names as lowercase with underscore, like the variables above this one. Should be like this in all the code for this PR.

2017-06-20 12:12 UTC, phillip-hopper approved these changes

2017-06-20 13:47 UTC, PhotoNomad0 commented on client/client_callback.py
> +        self.tempDir = tempfile.mkdtemp(suffix="", prefix="client_callback_")
@rich - OK Changed color settings in IntelliJ so that I will notice the warnings.  Made a ton of fixes.

2017-06-21 02:41 UTC, richmahn approved these changes

2017-06-21 13:54 UTC, richmahn approved these changes
LGTM 👍

2017-06-21 13:54 UTC, merged